In [1]:
import numpy as np
import os
import re
import pandas as pd

In [2]:
path = os.getcwd()
lessons = [folder for folder in os.listdir(path) if folder.split('_')[0] == 'lesson']
lessons

['lesson_10_1_files_read',
 'lesson_10_2_files_write',
 'lesson_10_3_files_append',
 'lesson_10_4_files_csv_read',
 'lesson_10_5_files_csv_write',
 'lesson_10_6_files_practice',
 'lesson_11_1_func_algorithms',
 'lesson_11_2_func_separate',
 'lesson_11_3_func_names',
 'lesson_11_4_func_tasks_with_strings',
 'lesson_11_5_func_tasks_with_dicts',
 'lesson_11_6_func_files_algo',
 'lesson_11_7_func_final',
 'lesson_12_1_module',
 'lesson_12_2_numpy',
 'lesson_12_3_matplotlib',
 'lesson_1_0_intro',
 'lesson_2_0_in_the_animal_world',
 'lesson_2_1_integer',
 'lesson_2_2_float',
 'lesson_2_3_bool',
 'lesson_2_4_type_conversion',
 'lesson_2_5_numbers_operations',
 'lesson_3_1_conditions',
 'lesson_3_2_else',
 'lesson_3_3_negation_operator',
 'lesson_3_4_operator_and',
 'lesson_3_5_operator_or',
 'lesson_3_6_comparison_operators',
 'lesson_3_7_elif',
 'lesson_3_8_nested',
 'lesson_4_1_while',
 'lesson_4_2_for',
 'lesson_5_1_strings',
 'lesson_5_2_slices',
 'lesson_5_3_operators',
 'lesson_5_4_methods',
 'lesson_6_1_lists_intro',
 'lesson_6_2_lists_get_elements',
 'lesson_6_3_lists_add_delete',
 'lesson_6_4_lists_slices',
 'lesson_6_5_lists_aggregations',
 'lesson_6_6_lists_sort',
 'lesson_6_7_lists_for',
 'lesson_6_8_lists_tuples',
 'lesson_6_9_lists_additional_methods',
 'lesson_7_1_dicts_intro',
 'lesson_7_2_dicts_get_data',
 'lesson_7_3_dicts_edit_add_delete',
 'lesson_7_4_dicts_values_keys',
 'lesson_7_5_dicts_items',
 'lesson_7_6_sets',
 'lesson_7_7_sets_methods',
 'lesson_7_8_dicts_sets_practice',
 'lesson_8_1_algorithms_lists',
 'lesson_8_2_filter_lists',
 'lesson_8_3_divide_into_groups',
 'lesson_8_4_transforming_list',
 'lesson_8_5_errors',
 'lesson_8_6_practice',
 'lesson_9_1_functions_without_params',
 'lesson_9_2_functions_with_params',
 'lesson_9_3_functions_return',
 'lesson_9_4_functions_args',
 'lesson_9_5_functions_corner_cases',
 'lesson_9_6_functions_sort',
 'lesson_9_7_functions_practice']

In [3]:
len(lessons)

67

In [190]:
pattern_1 = r'^problem_\d{1,2}\.md$'
pattern_2 = r'lesson_\d+_\d+_'

dct = {}

for lesson in lessons:
    # print(lesson)
    files = [name for name in os.listdir(lesson) if re.match(pattern_1, name)]
    # print(files)
    # print('number of problems', len(files))

    number = list(map(int, lesson.split('_')[1:3]))


    
    title = re.sub(pattern_2, '', lesson)

    # print(number)
    # print(title)
    # print()
    for i, problem in enumerate(files):

        path = os.path.join(lesson, problem)
        # print(path)
        file = open(path, 'r', encoding="utf8").read()
        file_len = len(file)

        dct_ = {'folder':lesson, 'lesson_n':number[0], 'series_n':number[1], 'problem_n':i+1, 'title':title, 'name':problem, 'file_len':file_len}
        dct[tuple(number+[i])] = dct_

df = pd.DataFrame(dct).T.sort_index()

In [193]:
df.to_csv('ploblem_len.csv')

In [227]:
df[df['lesson_n']==12]['file_len'].sum()

17714

In [228]:
count = {}

for lesson_n in (list(set(list(df['lesson_n'])))):
    series_n = len(list(set(list(df[df['lesson_n'] == lesson_n]['series_n']))))
    problem_n = len(df[df['lesson_n'] == lesson_n])

    total_len = (df[df['lesson_n'] == lesson_n]['file_len'].sum())
    
    count[lesson_n] = {'lesson #':lesson_n, 'series number':series_n, 'problems number':problem_n, 'total_len':total_len}

In [230]:

# print(count)

count_df = pd.DataFrame(count).T
count_df.to_csv('count.csv')
count_df

    lesson #  series number  problems number  total_len
1          1              1                5       2411
2          2              6               26       5932
3          3              8               34       6947
4          4              2               10       5434
5          5              4               24       8533
6          6              9               21       7171
7          7              8               23       4537
8          8              6               17       7203
9          9              7               21       6725
10        10              6               16      10829
11        11              7               16      11880
12        12              3               27      17714

In [ ]:
for i in range(len(df)):
    df.iloc[i]['num_ser_in_les'] = 
    df.iloc[i]['lesson_n']

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [170]:
count = {}
for i in range(len(df)):
    if df.index[i][0] not in count:
        count[df.index[i][0]] = 1
    else:
        count[df.index[i][0]] += 1

print(count)

for i in range(len(df)):
    df['problems in lesson'] = count[df.index[i][0]]

{1: 5, 2: 26, 3: 34, 4: 10, 5: 24, 6: 21, 7: 23, 8: 17, 9: 21, 10: 16, 11: 16, 12: 27}

In [171]:
df.head(20)

                               folder                title          name  \
1 0 0                lesson_1_0_intro                intro  problem_1.md
    1                lesson_1_0_intro                intro  problem_2.md
    2                lesson_1_0_intro                intro  problem_3.md
    3                lesson_1_0_intro                intro  problem_4.md
    4                lesson_1_0_intro                intro  problem_5.md
2 0 0  lesson_2_0_in_the_animal_world  in_the_animal_world  problem_1.md
    1  lesson_2_0_in_the_animal_world  in_the_animal_world  problem_2.md
    2  lesson_2_0_in_the_animal_world  in_the_animal_world  problem_3.md
    3  lesson_2_0_in_the_animal_world  in_the_animal_world  problem_4.md
  1 0              lesson_2_1_integer              integer  problem_1.md
    1              lesson_2_1_integer              integer  problem_2.md
    2              lesson_2_1_integer              integer  problem_3.md
    3              lesson_2_1_integer              integer  problem_4.md
    4              lesson_2_1_integer              integer  problem_5.md
  2 0                lesson_2_2_float                float  problem_1.md
    1                lesson_2_2_float                float  problem_2.md
    2                lesson_2_2_float                float  problem_3.md
    3                lesson_2_2_float                float  problem_4.md
    4                lesson_2_2_float                float  problem_5.md
  3 0                 lesson_2_3_bool                 bool  problem_1.md

      file_len  problems in lesson
1 0 0      369                  27
    1      744                  27
    2      512                  27
    3      382                  27
    4      404                  27
2 0 0      202                  27
    1      154                  27
    2      172                  27
    3      157                  27
  1 0      152                  27
    1      118                  27
    2       82                  27
    3       86                  27
    4       75                  27
  2 0      155                  27
    1      369                  27
    2      489                  27
    3      355                  27
    4      368                  27
  3 0      145                  27